### ISSUE TITLE
Multi-character delimiters?

### ISSUE THREAD

**Issue by mblais** [fskorzec/vscode-shadow-align#1]
Hi, thanks for the great extension! :)

One thing it does not handle is this scenario:
```
const a = 123;
bcd += 1;
efg.hij -= 2;
```
I would want to it align like this, by the `=`:
```
const a  = 123;
bcd     += 1;
efg.hij -= 2;
x        = foo;
```
This does not seem possible - if aligning the `=`, the extension inserts spaces in the middle of `+=` and `-=`.

But it could work if the templates allowed regex on the right side, e.g.:
`"[^=]+[ +-]=", [ "[ +-]=" ]`
or:
`"[^=]+([ +-]=)", [ "$1" ]`

This would be a useful capability!

Thanks for your contributions, and for your consideration.

**Comment by NoMoreDeps** [comment]
Hi, yes indeed. I'm working on a better way to split by regex too as delimiter, with optional groups.
This will adress your issue.

Next release will be in about one week

**Comment by mblais** [comment]
If we could use (groups) in the filter regex and use the match references (e.g. $1, $2) in the column-def strings, that would be awesome - it would allow formatting things like jsDoc comments :

````
/**
 * Check getValue() at every RAF frame, waiting until it doesn't change
 * for minFrames frames in a row; Then call done().
 *
 * @param {function} getValue      - callback returns the value to check for stability.                             
 * @param {function} done          - callback when getValue() stops changing.                                       
 * @param {number}   [numFrames=2] - getValue() must not change for this many frames to be considered done changing.
 */

**Comment by NoMoreDeps** [comment]
Yeah,
I'm thinking we can acheive this kind of result. I am testing something...

**Comment by NoMoreDeps** [comment]
Yep it's working !!!!

**Comment by NoMoreDeps** [comment]
Needs some advanced tests tomorow, I will push it

With this configuration : 
`"(?<param>\\s*\\*\\s*@param)\\s*(?<type>\\{.*?\\})\\s*(?<name>.*?)(?<sep>-)\\s*(?<desc>.*)" : ["param","type","name","sep","desc"]`

And this text : 

```
 * @param {function} getValue- callback returns the value to check for stability.                             
 * @param {function} done- callback when getValue() stops changing.                                       
 * @param {number}[numFrames=2] - getValue() must not change for this many frames to be considered done changing.
```

you got this 

```
 * @param {function} getValue      - callback returns the value to check for stability.                             
 * @param {function} done          - callback when getValue() stops changing.                                       
 * @param {number}   [numFrames=2] - getValue() must not change for this many frames to be considered done changing.
```

**Comment by NoMoreDeps** [comment]
It is published

**Comment by mblais** [comment]
Excellent! 👍 

For your example, this might be better:
````
    "shadow.align.rgxTemplates": {
        "(?<param>\\s*\\*\\s*@param|@member)\\s*(?<type>\\{[^ -]*?\\})\\s*(?<name>[^ -]*)(?<sep>-)?\\s*(?<desc>.*)?" : ["param","type","name","sep","desc"],
    },
````
It also includes jsDoc lines without any comment.

**Comment by NoMoreDeps** [comment]
Yeah, you're right.
I'm open to suggestion
